version: "3"
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    # 権限の有効化
    privileged: true
    volumes:
      - ../:/workspaces
    command: /sbin/init ## これ
